# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e8b9deac64358594106f4edbc5ddf1233c13ff1acaa8d996db5dd0b8613f3e29b28e517f9379ec2e70b44779a660e91d4539af3148db2ddfd203b2c8928586

test:
  secret_key_base: 058ffb95e4d7473c5e0e44f420f658479795a5cd8828341157c5fd80e773425247c77fd22d27a5f01b220aece70084103702faf6a2acf981a60f1841d45d4d14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
